version: '2'
volumes:
  settings:
  chrome_data:
services:
  wifi-connect:
    image: xerofuzzion/wifi-connect:latest-aarch64
    restart: always
    network_mode: host
    privileged: true
    environment:
      - PORTAL_SSID=mvda-lounge-display-wifi-portal
      - PORTAL_PASSPHRASE=mountainviewmasoniclodge
      - DBUS_SYSTEM_BUS_ADDRESS="unix:path=/host/run/dbus/system_bus_socket"
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    cap_add:
        - NET_ADMIN
  kiosk:
    restart: always
    image: xerofuzzion/lounge_kiosks:latest-aarch64
    privileged: true
    ports:
      - 9222:9222
      - 9223:9223
    volumes:
      - 'settings:/data'
      - 'chrome_data:/chrome-data'
    environment:
      LAUNCH_URL: "mountainviewmasoniclodge.com"
      LAUNCH_URL_HDMI: "https://www.google.com"
    depends_on:
      - wifi-connect
  lounge_display:
    image: xerofuzzion/lounge_display_server:latest-aarch64
    restart: always
    ports:
      - "8080:8080"
    environment:
      - HOST_IP=${HOST_IP}
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      - KIOSK_IP=kiosk
    volumes:
      - ./oauth:/oauth
      - ./logs:/app/logs
  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: lgtm
    ports:
      - "3000:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC ingest
    environment:
      - PROMETHEUS_EXTRA_ARGS=--storage.tsdb.retention.time=60d
    volumes:
      - ./loki-config.yaml:/otel-lgtm/loki-config.yaml:ro
      - ./tempo-config.yaml:/otel-lgtm/tempo-config.yaml:ro

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"   # OTLP http for frontend telemetry
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - lgtm
