receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'node_exporter'
          scrape_interval: 15s
          static_configs:
            - targets: ['node_exporter:9100']

exporters:
  otlp/lgtm:
    endpoint: lgtm:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/lgtm, debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlp/lgtm, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/lgtm, debug]
